# Generated by Django 6.0.3 on 2026-05-17 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type_code', models.CharField(help_text="3-character code used in case numbers, e.g. '100'.", max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_department', models.ForeignKey(blank=True, help_text='Default destination department for this template.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_templates', to='departments.department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoutingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_rules', to='departments.department')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_rules', to='templates_cfg.documenttemplate')),
            ],
            options={
                'ordering': ['template', 'priority'],
                'unique_together': {('template', 'department')},
            },
        ),
        migrations.CreateModel(
            name='TemplateAttachmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_required', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_attachment_types', to='templates_cfg.documenttemplate')),
            ],
            options={
                'unique_together': {('template', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TemplateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_required', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_fields', to='templates_cfg.documenttemplate')),
            ],
            options={
                'unique_together': {('template', 'field_name')},
            },
        ),
    ]
