# Generated by Django 6.0.3 on 2026-05-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_cfg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='type_code',
            field=models.CharField(blank=True, help_text='Auto-generated 3-digit code used in case numbers (YY-TTT-NNNNN).', max_length=10, unique=True),
        ),
    ]
